services:
    david63.prunelog.listener:
        class: david63\prunelog\event\listener
        arguments:
            - @config
            - @request
        tags:
            - { name: event.listener }

    cron.task.core.prune_log:
        class: david63\prunelog\cron\task\core\prune_log
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
            - @log
            - @user
        calls:
            - [set_name, [cron.task.core.prune_log]]
        tags:
            - { name: cron.task }
